export const financeExplorerMapStyle = {
  version: 8,
  sources: {
    ne2_shaded: {
      maxzoom: 6,
      tileSize: 256,
      tiles: [
        "https://tiles.openfreemap.org/natural_earth/ne2sr/{z}/{x}/{y}.png",
      ],
      type: "raster",
    },
    openmaptiles: {
      type: "vector",
      url: "https://tiles.openfreemap.org/planet",
    },
  },
  layers: [
    {
      id: "background",
      type: "background",
      paint: {
        "background-color": "rgb(242,243,240)",
      },
    },
    {
      id: "ne2-shaded",
      type: "raster",
      source: "ne2_shaded",
      paint: {
        "raster-opacity": 0.55,
      },
    },
    {
      id: "park",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "park",
      paint: {
        "fill-color": "rgb(230, 233, 229)",
      },
    },
    {
      id: "water",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "water",
      paint: {
        "fill-color": "rgb(192, 230, 249)",
      },
    },
    {
      id: "landuse_residential",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landuse",
      filter: ["==", ["get", "class"], "residential"],
      paint: {
        "fill-color": "rgb(234, 234, 230)",
        "fill-opacity": [
          "interpolate",
          ["exponential", 0.6],
          ["zoom"],
          8,
          0.8,
          9,
          0.6,
        ],
      },
    },
    {
      id: "landcover_wood",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "landcover",
      minzoom: 10,
      filter: ["==", ["get", "class"], "wood"],
      paint: {
        "fill-color": "rgb(220,224,220)",
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          8,
          0,
          12,
          1,
        ],
      },
    },
    {
      id: "waterway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "waterway",
      paint: {
        "line-color": "hsl(195,17%,78%)",
        "line-width": 1.1,
      },
    },
    {
      id: "building",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "building",
      minzoom: 12,
      paint: {
        "fill-color": "rgb(234, 234, 229)",
        "fill-outline-color": "rgb(219, 219, 218)",
      },
    },
    {
      id: "aeroway-area",
      type: "fill",
      source: "openmaptiles",
      "source-layer": "aeroway",
      minzoom: 4,
      filter: [
        "match",
        ["get", "class"],
        ["runway", "taxiway"],
        true,
        false,
      ],
      paint: {
        "fill-color": "rgba(255,255,255,1)",
        "fill-opacity": [
          "interpolate",
          ["linear"],
          ["zoom"],
          13,
          0,
          14,
          1,
        ],
      },
    },
    {
      id: "highway_minor",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 8,
      filter: [
        "match",
        ["get", "class"],
        ["minor", "service", "track"],
        true,
        false,
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "hsl(0,0%,88%)",
        "line-opacity": 0.9,
        "line-width": [
          "interpolate",
          ["exponential", 1.55],
          ["zoom"],
          13,
          1.8,
          20,
          20,
        ],
      },
    },
    {
      id: "highway_major_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 11,
      filter: [
        "match",
        ["get", "class"],
        ["primary", "secondary", "tertiary", "trunk"],
        true,
        false,
      ],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
      },
      paint: {
        "line-color": "rgb(213, 213, 213)",
        "line-width": [
          "interpolate",
          ["exponential", 1.3],
          ["zoom"],
          10,
          3,
          20,
          23,
        ],
      },
    },
    {
      id: "highway_major_inner",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 11,
      filter: [
        "match",
        ["get", "class"],
        ["primary", "secondary", "tertiary", "trunk"],
        true,
        false,
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "#fff",
        "line-width": [
          "interpolate",
          ["exponential", 1.3],
          ["zoom"],
          10,
          2,
          20,
          20,
        ],
      },
    },
    {
      id: "highway_major_subtle",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      maxzoom: 11,
      filter: [
        "match",
        ["get", "class"],
        ["primary", "secondary", "tertiary", "trunk"],
        true,
        false,
      ],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": "hsla(0,0%,85%,0.69)",
        "line-width": 2,
      },
    },
    {
      id: "highway_motorway_casing",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 6,
      filter: ["==", ["get", "class"], "motorway"],
      layout: {
        "line-cap": "butt",
        "line-join": "miter",
      },
      paint: {
        "line-color": "rgb(213, 213, 213)",
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          5.8,
          0,
          6,
          3,
          20,
          40,
        ],
      },
    },
    {
      id: "highway_motorway_inner",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 6,
      filter: ["==", ["get", "class"], "motorway"],
      layout: {
        "line-cap": "round",
        "line-join": "round",
      },
      paint: {
        "line-color": [
          "interpolate",
          ["linear"],
          ["zoom"],
          5.8,
          "hsla(0,0%,85%,0.53)",
          6,
          "#fff",
        ],
        "line-width": [
          "interpolate",
          ["exponential", 1.4],
          ["zoom"],
          4,
          2,
          6,
          1.3,
          20,
          30,
        ],
      },
    },
    {
      id: "railway",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 8,
      filter: ["==", ["get", "class"], "rail"],
      layout: {
        "line-join": "round",
      },
      paint: {
        "line-color": "#dddddd",
        "line-width": [
          "interpolate",
          ["exponential", 1.3],
          ["zoom"],
          8,
          1,
          16,
          3,
          20,
          7,
        ],
      },
    },
    {
      id: "railway_dashline",
      type: "line",
      source: "openmaptiles",
      "source-layer": "transportation",
      minzoom: 8,
      filter: ["==", ["get", "class"], "rail"],
      layout: {
        "line-join": "round",
      },
      paint: {
        "line-color": "#fafafa",
        "line-dasharray": [3, 3],
        "line-width": [
          "interpolate",
          ["exponential", 1.3],
          ["zoom"],
          8,
          0.8,
          16,
          2,
          20,
          6,
        ],
      },
    },
  ],
};
